sport_map:
  generic: "一般"
  running: "跑步"
  cycling: "騎乘"
  swimming: "游泳"
  walking: "步行"
  training: "訓練"
  yoga: "瑜伽"
  hiking: "登山/健行"
  fitness_equipment: "健身器材"
  multisport: "多項運動"
  hiit: "高強度間歇訓練"
  cardio_training: "有氧訓練"
  pilates: "普拉提"
  strength_training: "肌力訓練"
  rowing: "划船"
  climbing: "攀岩"
  cross_country_skiing: "越野滑雪"
  mountaineering: "登山"
  snowboarding: "單板滑雪"
  skiing: "雙板滑雪"
  skating: "溜冰"
  paddlesports: "划船運動"
  driving: "駕駛"

sub_sport_map:
  generic: "一般"
  treadmill: "跑步機"
  street: "街道"
  trail: "越野"
  track: "田徑場"
  indoor_cycling: "室內騎乘"
  mountain: "山區"
  road: "公路"
  pool_swimming: "泳池游泳"
  open_water: "開放水域游泳"
  strength_training: "肌力訓練"
  cardio_training: "有氧訓練"
  hiit: "高強度間歇"
  pilates: "普拉提"
  stair_climbing: "爬樓梯"
  elliptical: "滑步機"
  rowing: "室內划船"
  indoor_walking: "室內步行"
  obstacle_course: "障礙賽"
  speed_walking: "競走"
  lap_swimming: "泳池游泳"
  yoga: "瑜伽"
